# --- BUILD STAGE ---
FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

# --- STATIC ASSETS ---
FROM alpine:latest
WORKDIR /var/www/frontend
COPY --from=build /app/dist ./
CMD ["tail", "-f", "/dev/null"]
